"""add unique constraint refreshtoken

Revision ID: 016f4a088acb
Revises: ee787e242312
Create Date: 2025-04-11 19:51:33.684387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016f4a088acb'
down_revision: Union[str, None] = 'ee787e242312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_token_user_id_key', 'refresh_token', type_='unique')
    op.drop_constraint('refresh_token_value_key', 'refresh_token', type_='unique')
    op.create_unique_constraint('uq_id_ip_user_agent', 'refresh_token', ['user_id', 'ip_address', 'user_agent'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_id_ip_user_agent', 'refresh_token', type_='unique')
    op.create_unique_constraint('refresh_token_value_key', 'refresh_token', ['value'])
    op.create_unique_constraint('refresh_token_user_id_key', 'refresh_token', ['user_id'])
    # ### end Alembic commands ###
