"""change enum name

Revision ID: 3a0abdaa9252
Revises: eebbb601993a
Create Date: 2025-04-17 20:04:05.179860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a0abdaa9252'
down_revision: Union[str, None] = 'eebbb601993a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

device_type_enum = sa.Enum('MOBILE', 'TABLET', 'PC',
                           'BOT', 'UNKNOWN', name='device_type')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    device_type_enum.create(op.get_bind(), checkfirst=True)
    op.execute("""
                ALTER TABLE refresh_token
                ALTER COLUMN user_agent
                TYPE device_type
                USING user_agent::text::device_type
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_token', 'user_agent',
                    existing_type=sa.Enum(
                        'MOBILE', 'TABLET', 'PC', 'BOT', 'UNKNOWN', name='device_type'),
                    type_=postgresql.ENUM(
                        'local', 'google', 'github', name='auth_provider'),
                    existing_nullable=False)
    # ### end Alembic commands ###
