"""Add new column provider

Revision ID: b9036318c452
Revises: e3556e6e2e4b
Create Date: 2025-04-05 14:02:32.526939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9036318c452'
down_revision: Union[str, None] = 'e3556e6e2e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

auth_provider_enum = sa.Enum('local', 'google', 'github', name='auth_provider')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    auth_provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('provider', sa.Enum('local', 'google', 'github', name='auth_provider'), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
