"""change column name refreshtoken

Revision ID: eebbb601993a
Revises: 016f4a088acb
Create Date: 2025-04-16 20:35:59.099742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebbb601993a'
down_revision: Union[str, None] = '016f4a088acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.drop_column('refresh_token', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('refresh_token', 'token_hash')
    # ### end Alembic commands ###
