import type { ComponentType } from 'react';
import {
  Armchair,
  Baby,
  Bike,
  Book,
  Bus,
  Car,
  CircleParking,
  Clapperboard,
  Coffee,
  Croissant,
  Dog,
  Drama,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  GraduationCap,
  Headphones,
  HeartPulse,
  Home,
  Keyboard,
  Landmark,
  Lightbulb,
  Monitor,
  Music,
  Palette,
  Pill,
  Plane,
  Scissors,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  TicketsPlane,
  Ticket,
  Droplets,
  Utensils,
  Wifi,
  Wrench,
  Gift,
} from 'lucide-react';
import { normalizeText } from './text';

type IconComponent = ComponentType<{ size?: number | string; className?: string }>;

const BY_GROUP: Record<string, IconComponent> = {
  condominio: Landmark,
  agua: Droplets,
  luz: Lightbulb,
  gas: Flame,
  internet: Wifi,
  manutencao: Wrench,
  moveis: Armchair,
  padaria: Croissant,
  cafe: Coffee,
  mercado: ShoppingCart,
  'transporte publico': Bus,
  uber: Car,
  'manutencao veiculo': Wrench,
  estacionamento: CircleParking,
  pedagio: Car,
  financiamento: Landmark,
  'seguro veiculo': Car,
  farmacia: Pill,
  consulta: Stethoscope,
  academia: Dumbbell,
  cinema: Film,
  viagens: Plane,
  hobbies: Palette,
  'barbearia/salao': Scissors,
  netflix: Clapperboard,
  spotify: Music,
  ifood: Utensils,
  show: Ticket,
  cursos: GraduationCap,
  livros: Book,
  roupa: Shirt,
  'cuidados pessoais': Sparkles,
  presente: Gift,
  pets: Dog,
};

const BY_KEYWORD: [string, IconComponent][] = [
  ['autom', Car],
  ['carro', Car],
  ['veicul', Car],
  ['combustiv', Fuel],
  ['gasolina', Fuel],
  ['aliment', Utensils],
  ['comida', Utensils],
  ['restaurant', Utensils],
  ['lanche', Utensils],
  ['delivery', Utensils],
  ['stream', Clapperboard],
  ['assinatura', Clapperboard],
  ['teclad', Keyboard],
  ['mouse', Keyboard],
  ['headset', Headphones],
  ['fone', Headphones],
  ['monitor', Monitor],
  ['celular', Smartphone],
  ['telefone', Smartphone],
  ['saude', HeartPulse],
  ['medic', Stethoscope],
  ['casa', Home],
  ['moradia', Home],
  ['aluguel', Home],
  ['transporte', Bus],
  ['bicicleta', Bike],
  ['viagem', TicketsPlane],
  ['estudo', GraduationCap],
  ['educacao', GraduationCap],
  ['lazer', Drama],
  ['musica', Music],
  ['pet', Dog],
  ['filho', Baby],
  ['bebe', Baby],
  ['roupa', Shirt],
  ['mercado', ShoppingCart],
  ['compra', ShoppingCart],
];

export function resolveExpenseIcon(group: string | null): IconComponent {
  if (!group) return Tag;
  const key = normalizeText(group);
  const exact = BY_GROUP[key];
  if (exact) return exact;
  const match = BY_KEYWORD.find(([needle]) => key.includes(needle));
  return match ? match[1] : Tag;
}
